### ISSUE TITLE
Remote or in person? 

### ISSUE THREAD

**Issue by JeneciaMartinez** [JIFGeorgetown/apply#2]
# Summary #

Hello, Is the fellowship remote (aside from the in-person 5-day training at the start of the program in DC)? Or does it require fellows to live in DC? Thank you!

**Comment by jtashea** [comment]
Hi Jenecia. Thank you for your question. The fellowship is an opportunity to embed (ie. work in-person) with a court in the US. We received applications from every geographic region, and we're working on selecting project sites now.

**Comment by JeneciaMartinez** [comment]
Thank you!
